
### User 
### GET Method 
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDI5OTg3NTQsImV4cCI6MTc0MzA4NTE1NH0.I7Qf_2BoCVw07dMTR5LtNO_r0CYLGyLTKIEiKlS__to   
    
### POST Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json    

{"name": "Sameer",
"email": "sameer@gmal.com",
"password": "dhading"
}
    

## User Login
### POST Method
POST http://localhost:8000/api/v1/users/login     
Content-Type: application/json

{
    "email":"kiranl@gmail.com",    
    "password":"adamghat"       
}
### Transactions

### Post Transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDI3MDc4ODAsImV4cCI6MTc0Mjc5NDI4MH0.MTD8fXmVPGZF5k8UhkiK0ypVdkcOJi_ZG1QXjq7nbIo

{
    "title":"salary",
    "amount":333,
    "tdate":"2022-09-22"
}


### Get Transaction
GET http://localhost:8000/api/v1/transactions 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDI5OTg3NTQsImV4cCI6MTc0MzA4NTE1NH0.I7Qf_2BoCVw07dMTR5LtNO_r0CYLGyLTKIEiKlS__to

### Delete Transaction
DELETE  http://localhost:8000/api/v1/transactions 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDI5OTg3NTQsImV4cCI6MTc0MzA4NTE1NH0.I7Qf_2BoCVw07dMTR5LtNO_r0CYLGyLTKIEiKlS__to

["67e15b95d4464aeb6121f7e3"]

