
### User 
### GET Method 
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDIyNzI1NjEsImV4cCI6MTc0MjM1ODk2MX0.VbCjKAKW68P2N8UNBQiq8keSDrhWSDHf4iTpf5FmTe
    
### POST Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json    

{"name": "kiran",
"email": "kiran@gmal.com",
"password": "aaa"
}
    

## User Login
### POST Method
POST http://localhost:8000/api/v1/users/login     
Content-Type: application/json

{
    "email":"kiranl@gmail.com",    
    "password":"adamghat"       
}
### Transactions

