
### User 
### GET Method 
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDIyNzI1NjEsImV4cCI6MTc0MjM1ODk2MX0.VbCjKAKW68P2N8UNBQiq8keSDrhWSDHf4iTpf5FmTeM   
    
### POST Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json    

{"name": "kiran",
"email": "kiran@gmal.com",
"password": "aaa"
}
    

## User Login
### POST Method
POST http://localhost:8000/api/v1/users/login     
Content-Type: application/json

{
    "email":"kiranl@gmail.com",    
    "password":"adamghat"       
}
### Transactions

### Post Transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpcmFubEBnbWFpbC5jb20iLCJpYXQiOjE3NDI3MDc4ODAsImV4cCI6MTc0Mjc5NDI4MH0.MTD8fXmVPGZF5k8UhkiK0ypVdkcOJi_ZG1QXjq7nbIo

{
    "title":"salary",
    "amount":333,
    "tdate":"2022-09-22"
}


